# Generated by Django 5.2.6 on 2025-10-15 15:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultUser',
            fields=[
            ],
            options={
                'verbose_name': 'Adult User',
                'verbose_name_plural': 'Adult Users',
                'ordering': ['username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
